version: '3'
services:
  onlyoffice:
    image: onlyoffice/documentserver:8.1
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_SECRET}
    volumes:
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/App_Data:/var/lib/onlyoffice/documentserver/App_Data
    ports:
      - '8890:80'
    networks:
      allio_office_net:
        ipv4_address: 172.32.0.2

  office-service:
    container_name: office-service
    image: ${REGISTRY}/office-service:${VERSION}
    environment:
      - TZ=Asia/Shanghai
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - OSS_ENDPOINT=${OSS_ENDPOINT}
      - OSS_ACCESS_KEY=${OSS_ACCESS_KEY}
      - OSS_SECRET_KEY=${OSS_SECRET_KEY}
      - OSS_BUCKET=${OSS_BUCKET}
      - DOCUMENT_SERVER_URL=${DOCUMENT_SERVER_URL}
      - ONLYOFFICE_SERVER_URL=${ONLYOFFICE_SERVER_URL}
      - ONLYOFFICE_SECRET=${ONLYOFFICE_SECRET}
    ports:
      - '8700:8700'
    privileged: true
    restart: always
    networks:
      allio_office_net:
        ipv4_address: 172.32.0.3
    depends_on:
      - onlyoffice

  office-web:
    container_name: office-web
    image: ${REGISTRY}/office-web:${VERSION}
    environment:
      - TZ=Asia/Shanghai
      - NEXT_PUBLIC_API_URL=${DOCUMENT_SERVER_URL}
    ports:
      - '8230:3000'
    privileged: true
    restart: always
    networks:
      allio_office_net:
        ipv4_address: 172.32.0.4
    depends_on:
      - onlyoffice
      - office-service

networks:
  allio_office_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/24
